[package]
authors     = ["chance dinkins"]
description = "core logic and types for grill"
edition     = "2021"
license     = "MIT OR Apache-2.0"
name        = "grill-core"
repository  = "https://github.com/chanced/grill"
version     = "0.1.0"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
anyhow           = { workspace = true }
async-trait      = { workspace = true }
bitflags         = { workspace = true }
dyn-clone        = { workspace = true }
either           = { workspace = true }
erased-serde     = { workspace = true }
grill-macros     = { workspace = true }
inherent         = { workspace = true }
jsonptr          = { workspace = true }
num              = { workspace = true }
num-rational     = { workspace = true }
once_cell        = { workspace = true }
paste            = { workspace = true }
percent-encoding = { workspace = true }
regex            = { workspace = true }
reqwest          = { workspace = true, optional = true }
serde            = { workspace = true }
serde_json       = { version = "1.0.106", features = ["arbitrary_precision"] }
serde_yaml       = { workspace = true, optional = true }
slotmap          = { workspace = true }
strum            = { workspace = true }
thiserror        = { workspace = true }
toml             = { workspace = true, optional = true }
url              = { workspace = true }
urn              = { workspace = true }

[dev-dependencies]
grill   = { workspace = true }
mockall = { workspace = true }
similar = { workspace = true }
tokio   = { version = "1.28", features = ["full"] }

[features]
default = []
http    = ["reqwest"]
toml    = ["dep:toml"]
yaml    = ["dep:serde_yaml"]

[replace]
"serde_json:1.0.106" = { git = "https://github.com/serde-rs/json" }
