[workspace]
members = ["grill", "tests"]

[workspace.dependencies]
grill = { path = "grill" }

anymap           = { version = "1.0.0-beta.2" }
async-trait      = { version = "0.1" }
big-rational-str = { version = "0.1.6" }
dyn-clone        = { version = "1.0.11" }
erased-serde     = { version = "0.3.25" }
fancy-regex      = { version = "0.11.0" }
inherent         = { version = "1" }
itertools        = { version = "0.10" }
jsonptr          = { version = "0.4", features = ["url"] }
num              = { version = "0.4", features = ["serde"] }
num-rational     = { version = "0.4.1" }
once_cell        = { version = "1.10" }
percent-encoding = { version = "2.3" }
petgraph         = { version = "0.6" }
reqwest          = { version = "0.11" }
serde            = { version = "1.0.163", features = ["derive", "rc"] }
serde_json       = { version = "1.0", features = ["arbitrary_precision"] }
serde_yaml       = { version = "0.9.21" }
slotmap          = { version = "1.0.6" }
snafu            = { version = "0.7.4" }
strum            = { version = "0.24", features = ["derive"] }
strum_macros     = { version = "0.24" }
toml             = { version = "0.7.4" }
url              = { version = "2.2.2" }
urn              = { version = "0.7.0" }

mockall = { version = "0.11" }
