[package]
authors     = ["chance dinkins"]
description = "wip"
edition     = "2021"
license     = "MIT OR Apache-2.0"
name        = "grill"
repository  = "https://github.com/chanced/grill"
version     = "0.0.0"

[dependencies]
async-trait     = { version = "0.1" }
async_fn_traits = { version = "0.1.1" }
dyn-clone       = { version = "1.0.11" }
either          = { version = "1.8" }
heck            = { version = "0.4" }
jsonptr         = { version = "0.3.3", features = ["uniresid", "url"] }
once_cell       = { version = "1.10" }
petgraph        = { version = "0.6" }
serde           = { version = "1", features = ["derive"] }
serde_json      = { version = "1.0" }
thiserror       = { version = "1.0" }
uniresid        = { version = "0.1.4" }
url             = { version = "2.2.2" }

[dev-dependencies]
tokio = { version = "1.28", features = ["full"] }
