[package]
edition = "2021"
name    = "grill-macros"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "1.0" }
syn         = { version = "2.0", features = ["full", "extra-traits"] }
