[package]
authors     = ["chance dinkins"]
description = "wip"
edition     = "2021"
license     = "MIT OR Apache-2.0"
name        = "grill"
repository  = "https://github.com/chanced/grill"
version     = "0.0.0"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
anymap           = { workspace = true }
async-trait      = { workspace = true }
big-rational-str = { version = "0.1.6" }
dashmap          = { workspace = true }
downcast-rs      = { version = "1.2.0" }
dyn-clone        = { workspace = true }
either           = { workspace = true }
fraction         = { workspace = true }
itertools        = { workspace = true }
jsonptr          = { workspace = true }
num              = { workspace = true }
num-rational     = { version = "0.4.1" }
once_cell        = { workspace = true }
petgraph         = { workspace = true }
reqwest          = { version = "0.11", optional = true }
serde            = { workspace = true }
serde_json       = { workspace = true, features = ["arbitrary_precision"] }
snafu            = { workspace = true }
strum            = { workspace = true }
strum_macros     = { workspace = true }
url              = { workspace = true }
# async_fn_traits = { version = "0.1.1" }
# regex        = { version = "1.8" }

[dev-dependencies]
criterion = { version = "0.4" }
tokio     = { version = "1.28", features = ["full"] }

[features]

default = ["http"]
http    = ["reqwest"]

[[bench]]
harness = false
name    = "benchmark"
